// <auto-generated />
using System;
using FilmGalaxy.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FilmGalaxy.DataAccess.Migrations
{
    [DbContext(typeof(DataDbContext))]
    [Migration("20250101172016_AddForeignKeyForCategoryMovieRelations")]
    partial class AddForeignKeyForCategoryMovieRelations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FilmGalaxy.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            DisplayOrder = 1,
                            Name = "Action"
                        },
                        new
                        {
                            CategoryId = 2,
                            DisplayOrder = 2,
                            Name = "Sci-Fi"
                        },
                        new
                        {
                            CategoryId = 3,
                            DisplayOrder = 3,
                            Name = "History"
                        });
                });

            modelBuilder.Entity("FilmGalaxy.Models.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovieId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ListPrice")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Price100")
                        .HasColumnType("float");

                    b.Property<double>("Price50")
                        .HasColumnType("float");

                    b.HasKey("MovieId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            CategoryId = 1,
                            Date = new DateOnly(2010, 7, 16),
                            Description = "A mind-bending thriller by Christopher Nolan.",
                            Director = "Christopher Nolan",
                            ListPrice = 14.99,
                            Name = "Inception",
                            Price = 9.9900000000000002,
                            Price100 = 7.9900000000000002,
                            Price50 = 8.9900000000000002
                        },
                        new
                        {
                            MovieId = 2,
                            CategoryId = 1,
                            Date = new DateOnly(2008, 7, 18),
                            Description = "The second installment in the Batman trilogy by Nolan.",
                            Director = "Christopher Nolan",
                            ListPrice = 16.989999999999998,
                            Name = "The Dark Knight",
                            Price = 11.99,
                            Price100 = 9.9900000000000002,
                            Price50 = 10.99
                        },
                        new
                        {
                            MovieId = 3,
                            CategoryId = 2,
                            Date = new DateOnly(1999, 3, 31),
                            Description = "A science fiction classic about simulated reality.",
                            Director = "The Wachowskis",
                            ListPrice = 12.99,
                            Name = "The Matrix",
                            Price = 8.9900000000000002,
                            Price100 = 6.9900000000000002,
                            Price50 = 7.9900000000000002
                        },
                        new
                        {
                            MovieId = 4,
                            CategoryId = 1,
                            Date = new DateOnly(2019, 4, 26),
                            Description = "The epic conclusion to the Infinity Saga.",
                            Director = "Anthony and Joe Russo",
                            ListPrice = 19.989999999999998,
                            Name = "Avengers: Endgame",
                            Price = 14.99,
                            Price100 = 12.99,
                            Price50 = 13.99
                        },
                        new
                        {
                            MovieId = 5,
                            CategoryId = 3,
                            Date = new DateOnly(1997, 12, 19),
                            Description = "A love story set during the ill-fated voyage of the Titanic.",
                            Director = "James Cameron",
                            ListPrice = 18.989999999999998,
                            Name = "Titanic",
                            Price = 13.99,
                            Price100 = 11.99,
                            Price50 = 12.99
                        },
                        new
                        {
                            MovieId = 6,
                            CategoryId = 2,
                            Date = new DateOnly(1972, 3, 24),
                            Description = "A powerful family drama set in the world of organized crime.",
                            Director = "Francis Ford Coppola",
                            ListPrice = 15.99,
                            Name = "The Godfather",
                            Price = 10.99,
                            Price100 = 8.9900000000000002,
                            Price50 = 9.9900000000000002
                        },
                        new
                        {
                            MovieId = 7,
                            CategoryId = 3,
                            Date = new DateOnly(1994, 7, 6),
                            Description = "The life story of a man with a low IQ but a big heart.",
                            Director = "Robert Zemeckis",
                            ListPrice = 13.99,
                            Name = "Forrest Gump",
                            Price = 9.9900000000000002,
                            Price100 = 7.9900000000000002,
                            Price50 = 8.9900000000000002
                        },
                        new
                        {
                            MovieId = 8,
                            CategoryId = 2,
                            Date = new DateOnly(1993, 6, 11),
                            Description = "A groundbreaking film about a dinosaur theme park gone wrong.",
                            Director = "Steven Spielberg",
                            ListPrice = 14.99,
                            Name = "Jurassic Park",
                            Price = 10.99,
                            Price100 = 8.9900000000000002,
                            Price50 = 9.9900000000000002
                        },
                        new
                        {
                            MovieId = 9,
                            CategoryId = 2,
                            Date = new DateOnly(1994, 10, 14),
                            Description = "A unique and nonlinear crime drama by Quentin Tarantino.",
                            Director = "Quentin Tarantino",
                            ListPrice = 17.989999999999998,
                            Name = "Pulp Fiction",
                            Price = 12.99,
                            Price100 = 10.99,
                            Price50 = 11.99
                        },
                        new
                        {
                            MovieId = 10,
                            CategoryId = 3,
                            Date = new DateOnly(1994, 9, 22),
                            Description = "A man wrongfully convicted of murder forms a friendship in prison.",
                            Director = "Frank Darabont",
                            ListPrice = 16.989999999999998,
                            Name = "The Shawshank Redemption",
                            Price = 11.99,
                            Price100 = 9.9900000000000002,
                            Price50 = 10.99
                        });
                });

            modelBuilder.Entity("FilmGalaxy.Models.Movie", b =>
                {
                    b.HasOne("FilmGalaxy.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
